num1=float(input("Enter first number:"))
num2=float(input("Enter second number:"))
print("Addition: " +str(num1 + num2))
print("Subtraction: " +str(num1-num2))
print("Multiplication: " +str(num1*num2))
print("Division: "+str(num1/num2))